# Generated by Django 5.1.3 on 2024-11-12 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_options_post_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='image_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
